NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.buyerorg.commerce.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.buyerorg.commerce.com-cert.pem
    OrganizationalUnitIdentifier: peer
