# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

# make necessary changes for your orderer descriptions please refer to notes 

  orderer.commerce.com:
    container_name: orderer.commerce.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID= CommerceOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/commerce.com/orderers/orderer.commerce.com/msp:/var/hyperledger/orderer/msp # change the directory before : to your directory under cryptoconfig 
    - ../crypto-config/ordererOrganizations/commerce.com/orderers/orderer.commerce.com/tls/:/var/hyperledger/orderer/tls # change the directory before : to your directory under cryptoconfig 
    - orderer.commerce.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.buyerorg.commerce.com:
    container_name: peer0.buyerorg.commerce.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID= peer0.buyerorg.commerce.com
      - CORE_PEER_ADDRESS= peer0.buyerorg.commerce.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP= peer0.buyerorg.commerce.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT= peer0.buyerorg.commerce.com:7051
      - CORE_PEER_LOCALMSPID=BuyerOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyerorg.commerce.com/peers/peer0.buyerorg.commerce.com/msp:/etc/hyperledger/fabric/msp # change the directory before : to your directory under cryptoconfig 
        - ../crypto-config/peerOrganizations/buyerorg.commerce.com/peers/peer0.buyerorg.commerce.com/tls:/etc/hyperledger/fabric/tls # change the directory before : to your directory under cryptoconfig 
        - peer0.buyerorg.commerce.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060

  peer0.sellerorg.commerce.com:
    container_name: peer0.sellerorg.commerce.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sellerorg.commerce.com
      - CORE_PEER_ADDRESS=peer0.sellerorg.commerce.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sellerorg.commerce.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sellerorg.commerce.com:7051
      - CORE_PEER_LOCALMSPID=SellerOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sellerorg.commerce.com/peers/peer0.sellerorg.commerce.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sellerorg.commerce.com/peers/peer0.sellerorg.commerce.com/tls:/etc/hyperledger/fabric/tls
        - peer0.sellerorg.commerce.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060

  peer0.shipperorg.commerce.com:
    container_name: peer0.shipperorg.commerce.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shipperorg.commerce.com
      - CORE_PEER_ADDRESS=peer0.shipperorg.commerce.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shipperorg.commerce.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shipperorg.commerce.com:7051
      - CORE_PEER_LOCALMSPID=ShipperOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/shipperorg.commerce.com/peers/peer0.shipperorg.commerce.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/shipperorg.commerce.com/peers/peer0.shipperorg.commerce.com/tls:/etc/hyperledger/fabric/tls
        - peer0.shipperorg.commerce.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
      - 9055:6060

  peer0.financeorg.commerce.com:
    container_name: peer0.financeorg.commerce.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.financeorg.commerce.com
      - CORE_PEER_ADDRESS=peer0.financeorg.commerce.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.financeorg.commerce.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.financeorg.commerce.com:7051
      - CORE_PEER_LOCALMSPID=FinanceOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/financeorg.commerce.com/peers/peer0.financeorg.commerce.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/financeorg.commerce.com/peers/peer0.financeorg.commerce.com/tls:/etc/hyperledger/fabric/tls
        - peer0.financeorg.commerce.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
      - 10055:6060
