NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.sellerorg.commerce.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.sellerorg.commerce.com-cert.pem
    OrganizationalUnitIdentifier: peer
